version: "3.8"

volumes:
  mysql_data: {}
  mysql-data:
  web-sql:
  sql:

networks:
  hesoyamnet:
    name: hesoyamnet
    driver: bridge

services:
  integrationadapter:
      build: 
        context: .
        dockerfile: IntegrationAdapter/Dockerfile
      image: gregvader/integrationadapter:latest
      depends_on:
        - postgres
      restart: always
      environment: 
        DATABASE_HOST: postgres
        USES_POSTGRES: "TRUE"
        MyDbConnectionString: "Port=5432;Database=mydb1;User Id=username;Password=secret"
        shouldLogEvents: "false"
        appointmentEventLoggerURL: "irrelevant"
      volumes:
        - web-sql:/app/sql
      expose: 
        - "80"
      networks: 
        - hesoyamnet
      ports:
        - "5001:80"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
      - hesoyamnet
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb1
    volumes:
      - mysql-data:/var/lib/mysql