version: "3.8"

volumes:
  mysql_data: {}
  mysql-data:
  web-sql:
  sql:

networks:
  hesoyamnet:
    name: hesoyamnet
    driver: bridge

services:
  # Backend:
  #   build: 
  #     context: .
  #     dockerfile: Backend/Dockerfile
  #   image: gregvader/backend:latest
  #   volumes:
  #     - mysql_data:/var/lib/mysql/data
  #   expose: 
  #     - "5000"
  #   ports:
  #     - "5100:5000"

  # IntegrationAdapter:
  #   build: 
  #     context: .
  #     dockerfile: IntegrationAdapter/Dockerfile
  #   image: gregvader/integrationadapter:latest
  #   depends_on: 
  #     - Backend
  #   expose: 
  #     - "5000"
  #   ports:
  #     - "5101:5000"

  WebApplication:
    build: 
      context: .
      dockerfile: WebApplication/Dockerfile
    image: gregvader/webapplication:latest
    depends_on:
      - postgres
    restart: on-failure
    environment:
      DATABASE_HOST: postgres
      USES_POSTGRES: "TRUE"
      MyDbConnectionString: "Port=5432;Database=mydb1;User Id=username;Password=secret"
    volumes:
      - web-sql:/app/sql
    expose: 
      - "80"
    networks: 
      - hesoyamnet
    ports:
      - "5000:80"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
      - hesoyamnet
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb1
    volumes:
      - mysql-data:/var/lib/mysql
      #- ./app:/docker-entrypoint-initdb.d/

  # WebApplicationFront:
  #   build:
  #     context: .
  #     dockerfile: web-application-front/Dockerfile
  #   image: gregvader/webapplicationfront:latest
  #   depends_on:
  #     - WebApplicationTests
  #   expose:
  #     - "80"

  #   ports:
  #     - "5105:80"

  # IntegrationAdapterTests:
  #   build:
  #     context: . 
  #     dockerfile: IntegrationAdapterTests/Dockerfile
  #   image: gregvader/integrationadaptertests:latest
  #   depends_on:
  #     - IntegrationAdapter
  #   expose: 
  #     - "80"
  #   ports: 
  #     - "5103:5000"

  # WebApplicationTests:
  #   build:
  #     context: . 
  #     dockerfile: WebApplicationTests/Dockerfile
  #   image: gregvader/webapplicationtests:latest
  #   depends_on:
  #     - WebApplication
  #   expose: 
  #     - "5000"
  #   ports: 
  #     - "5104:5000"

