services:
  WebApplicationTests:
    build: 
      context: .
      dockerfile: WebApplicationTests/Dockerfile
    image: gregvader/webapplicationtests:latest
    depends_on:
      - postgres
    restart: on-failure
    environment:
      DATABASE_HOST: postgres
      USES_POSTGRES: "TRUE"
      MyDbConnectionString: "Port=5432;Database=mydb1;User Id=username;Password=secret"
    volumes:
      - web-sql:/app/sql
    expose: 
      - "80"
    networks: 
      - hesoyamnet
